import type { QuestionComponentProps } from '@/types/questionTypes';

export default function MatchingMatrix({ subSection, answers, onAnswer }: QuestionComponentProps) {
    const content = subSection.content as Record<string, any> | undefined;
    
    // 1. Determine options (from direct options, map_labels, or auto-generated from answer_format)
    let opts = { ...(subSection.options || content?.map_labels || {}) };
    let isAutoGenerated = false;
    const stem = subSection.question_text ?? subSection.question_stem ?? '';

    if (Object.keys(opts).length === 0) {
        const fmt = subSection.questions?.[0]?.answer_format || '';
        const match = fmt.match(/([A-Z])-([A-Z])/i);
        if (match) {
            isAutoGenerated = true;
            const startCode = match[1].toUpperCase().charCodeAt(0);
            const endCode = match[2].toUpperCase().charCodeAt(0);
            for (let i = startCode; i <= endCode; i++) {
                const letter = String.fromCharCode(i);
                opts[letter] = `Option ${letter}`;
            }
        } else {
            // Fallback if absolutely nothing is found
            ['A', 'B', 'C', 'D', 'E', 'F', 'G'].forEach(l => opts[l] = `Option ${l}`);
        }
    }

    const optionKeys = Object.keys(opts);
    const API_BASE = (import.meta.env.VITE_API_URL as string || 'http://localhost:5000/api').replace(/\/api$/, '');

    return (
        <div className="overflow-x-auto pb-4">
            {/* Shared stem */}
            {stem && (
                <p className="text-sm text-gray-700 font-medium mb-4 leading-relaxed">{stem}</p>
            )}

            {/* Render the Map/Diagram Image if provided */}
            {content?.image_key && (
                <div className="mb-6 flex justify-center">
                    <img
                        src={`${API_BASE}/api/cambridge-tests/stream?key=${encodeURIComponent(content.image_key)}`}
                        alt={content.map_description || "Diagram for labelling"}
                        className="max-w-full h-auto border border-gray-200 rounded-lg shadow-sm"
                    />
                </div>
            )}

            {/* Options chip grid (Legend for matching features) */}
            {!isAutoGenerated && Object.keys(opts).length > 0 && !content?.image_key && (
                <div className="grid grid-cols-2 gap-1.5 mb-6">
                    {Object.entries(opts).map(([k, v]) => (
                        <div key={k} className="bg-gray-50 border border-gray-200 rounded-lg px-2.5 py-1.5 text-xs text-gray-700">
                            <span className="font-bold text-gray-500 mr-1.5">{k}</span>{v as string}
                        </div>
                    ))}
                </div>
            )}

            {/* The Radio Matrix */}
            <div className="overflow-x-auto border border-gray-200 rounded-xl bg-white shadow-sm">
                <table className="w-full text-left border-collapse min-w-[400px]">
                    <thead>
                        <tr className="bg-gray-50 border-b border-gray-200">
                            <th className="py-3 px-3 text-sm font-semibold text-gray-400 font-mono w-12 text-center"></th>
                            <th className="py-3 px-3 text-sm font-semibold text-gray-700 min-w-[150px]"></th>
                            {optionKeys.map(opt => (
                                <th key={opt} className="py-3 px-1 text-sm font-bold text-gray-700 text-center w-12">
                                    {opt}
                                </th>
                            ))}
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                        {subSection.questions.map((q, idx) => {
                            const key = String(q.question_number);
                            const selected = answers[key] ?? '';
                            const isEven = idx % 2 === 0;

                            return (
                                <tr key={key} className={`transition-colors hover:bg-gray-50 ${!isEven ? 'bg-gray-50/30' : ''}`}>
                                    <td className="py-3 px-3 text-center">
                                        <span className="inline-flex items-center justify-center min-w-[24px] h-[24px] rounded-full bg-[#e6f4ea] text-[#1e8e3e] text-xs font-bold">
                                            {q.question_number}
                                        </span>
                                    </td>
                                    <td className="py-3 px-3 text-sm text-gray-700 font-medium pr-6 leading-relaxed">
                                        {q.question_text}
                                    </td>
                                    {optionKeys.map(opt => {
                                        const isSelected = selected === opt;
                                        return (
                                            <td key={opt} className="py-3 px-1 text-center">
                                                <button
                                                    onClick={() => onAnswer(q.question_number, opt)}
                                                    className={`w-5 h-5 rounded-full border flex items-center justify-center mx-auto transition-all ${isSelected
                                                        ? 'border-[#1e8e3e] bg-[#e6f4ea]'
                                                        : 'border-gray-300 hover:border-gray-400 bg-white'
                                                        }`}
                                                    aria-label={`Select option ${opt} for question ${q.question_number}`}
                                                >
                                                    {isSelected && <span className="w-2.5 h-2.5 bg-[#1e8e3e] rounded-full"></span>}
                                                </button>
                                            </td>
                                        );
                                    })}
                                </tr>
                            );
                        })}
                    </tbody>
                </table>
            </div>
        </div>
    );
}
